#ifndef RESULT2D_H
#define RESULT2D_H

#include "JSystem/JGeometry/Vec.h"
#include "JSystem/JKernel/JKRHeap.h"
#include "JSystem/JUtility/TColor.h"
#include "JSystem/JORReflexible.h"

#include "Kaneshige/HioMgr.h"
#include "Osako/kartPad.h"

class Result2DParam : public JORReflexible {
public:
    // Inline/Unused
    Result2DParam();
    virtual ~Result2DParam() {}
};

class Result2DHioNode : public HioNode {
public:
    Result2DHioNode();
    virtual ~Result2DHioNode() {}

    Result2DParam mParam;
};

class Result2D { // Autogenerated
public:

    struct data2D {
        data2D() {} // 0x80149ce8

        u8 _0[0xc];
    }; // size: 0xc

    Result2D(JKRHeap *); // 0x8014634c
    void init(); // 0x80149cec
    void draw(); // 0x8014a0e0
    void drawGP(); // 0x8014a184
    void drawVS(); // 0x8014a514
    void drawTA(); // 0x8014a838
    void drawMG(); // 0x8014ab54
    void calc(KartGamePad *); // 0x8014add0
    void calcRaceRank(); // 0x8014b2a0
    void calcGPRank(); // 0x8014b484
    void calcResult(); // 0x8014b634
    void calcVS(); // 0x8014b65c
    void calcTA(KartGamePad *); // 0x8014b798
    void calcMG(); // 0x8014bd30
    void calcPASSWD(KartGamePad *); // 0x8014be40
    void selectorGP(KartGamePad *); // 0x8014bf3c
    void selectorVS(KartGamePad *); // 0x8014c2f4
    void selectorTA(KartGamePad *); // 0x8014c480
    void selectorMG(KartGamePad *); // 0x8014c7a0
    void selectorCommon(); // 0x8014c924
    void setDrawGP(); // 0x8014c968
    void setDrawVS(); // 0x8014cb58
    void setDrawTA(); // 0x8014cc10
    void setDrawMG(); // 0x8014cd94
    int getResultSelector(); // 0x8014ce48
    void setRaceRank(); // 0x8014ce50
    void setGPRank(); // 0x8014d924
    void setVS(); // 0x8014df84
    void setTA(); // 0x8014e368
    void setMG(); // 0x8014eee4
    void setBattleCharacter(); // 0x8014f16c
    void getRaceRankLayoutAlpha(int, u8 &); // 0x8014f514
    void getGPRankLayoutAlpha(int, u8 &); // 0x8014f550
    void getRaceRankLinePos(int, int, f32 &); // 0x8014f594
    void getGPRankLinePos(int, int, f32 &); // 0x8014f71c
    void getResultLinePos(int, f32 &); // 0x8014f8a4
    void getRaceRankLineScale(int, int, JGeometry::TVec2f &, JGeometry::TVec2f &); // 0x8014f9d4
    void getGPRankLineScale(int, int, JGeometry::TVec2f &, JGeometry::TVec2f &); // 0x8014fb60
    void getFrameClr(int, JUTColor &, u8 &); // 0x8014fcf0
    void getVSPointYPos(int, int, f32 &); // 0x8014fedc
    void getMGPointYPos(int, f32 &); // 0x8014ff4c
    void getVSScale(int, f32 &); // 0x8014ffb8
    void getMGScale(int, f32 &); // 0x8014fff8
    void getVSColor(int, JUTColor &); // 0x80150038
    void getMGColor(int, JUTColor &); // 0x8015029c
    void getFrameColor(JUTColor &); // 0x80150500
    void getScale(int); // 0x8015057c
    void setScale(int); // 0x801505c4
    void setGPClr(); // 0x80150804
    bool getAnmEnd(); // 0x80150830
    
    static const u64 mSetWordLineTag[9]; // 0x8036ec18
    static const u64 mResultLayoutTag[11]; // 0x8036ec60
    static const u64 mResultLineTag[20]; // 0x8036ecb8
    static const u64 mGetPointTag[4]; // 0x8036ed58
    static const u64 mVSBattleCharacterTag[14]; // 0x8036ed78
    static const u64 mVSBattlePointTag[2]; // 0x8036ede8
    static const char *mRankName[8]; // 0x80394cc0
    static const char *mPlayerNumberName[4]; // 0x80394ce0
    static const char *mResultArrowName[3]; // 0x80394cf0
    static JUTColor mWhiteColor[4][2]; // 0x803fba20
    static bool mDrawFlag; // 0x804162e8
    static int mResultSelector; // 0x804162ec
    static int mResultState; // 0x804162f0
    static const u64 mOverBackTag; // 0x80418f80
    // Inline/Unused
    ~Result2D();
    void getCharPos(int);
private:
    PLACEHOLDER_BYTES(0, 0x197c);
    int _197c;                       // 0x197c
    PLACEHOLDER_BYTES(0x1980, 0x1988);
    f32 _1988;                       // 0x1988
    int _198c;                       // 0x198c
}; // class Result2D

#endif // RESULT2D_H
