#ifndef SCENEGHOSTLOADSAVE_H
#define SCENEGHOSTLOADSAVE_H

#include "JSystem/J2D/J2DScreen.h"
#include "Kameda/Scene.h"
#include "Kameda/SequenceInfo.h"
#include "Osako/SequenceApp.h"
#include "Osako/TARecord.h"
#include "types.h"


class SceneGhostLoadSave : public Scene { // Autogenerated
public:
    class Card {
    public:
        Card() {}

        void searchPane(u8, J2DScreen *); // 0x8018aa90
        void setCardInfo(); // 0x8018ada0
        void process(); // 0x8018af2c
        void unselect(); // 0x8018b2cc
        void insertCard(); // 0x8018b2fc
        void error(); // 0x8018b354
        void calcAnm(); // 0x8018b4a4

        // Inline/Unused
        void setBck(void *, J2DAnmTransform *);
        void setBpk(void *, J2DScreen *);
        void setBtk(void *, J2DScreen *);
        void setBrk(void *, J2DScreen *);
        void init();
        void probe();
        void mounting();
        void searchGhost();
        void checking();
        void frameIn();
        void frameOut();
        void selected();
        void selectable();
        void savable();
        void loadable();
        void selectIn();
        void selectOut();
        void noCard();


        static const u64 mscaPaneTag[9]; // 0x80375cf0
    };

    class GhostFileInfo {
    public:
        GhostFileInfo() {}
    };

    class GhostFileInfoTable {
    public:
        void append(s32, u32, TARecord &); // 0x8018a94c
        void convCrsID(u8); // 0x8018aa58

        // Inline/Unused
        void init();
        void numbering();
    };

    class GDInexLineVC {
    public:
        void setup(JKRArchive *, JKRHeap *, bool); // 0x8018cbe0
        void updateInfo(); // 0x8018d404

        // Inline/Unused
        void setGhostFileInfo(GhostFileInfo *);
        void selectIn();
        void selectOut();
        void selected();
        void unselect();
        void calcAnm();

        static const u64 mscaPaneTag[2]; // 0x80375df8
    };

    class GDIndexLayoutVC {
    public:
        void setup(JKRArchive *, JKRHeap *); // 0x8018d84c
        void setCard(Card *); // 0x8018db10
        void selectData(); // 0x8018dd68
        void scrollUp(); // 0x8018dfe8
        void scrollDown(); // 0x8018e01c
        void shiftUp(); // 0x8018e050
        void calcAnm(); // 0x8018e0ec

        // Inline/Unused
        void init(SequenceInfo::GhostSaveLoad);
        void frameIn();
        void frameOut();
        void shiftDown();
    };

    class SelectSlot {
    public:
        void setup(JKRArchive *, JKRHeap *); // 0x8018bc84
        void init(); // 0x8018c19c
        void processCard(); // 0x8018c444
        void watchCardState(); // 0x8018c498
        void selectSlot(); // 0x8018c6bc
        void frameIn(); // 0x8018cb90

        // Inline/Unused
        void initSelect(bool);
        void calcAnm();
        void isCardChecking();
        void existSavableCard();
        void existLoadableCard();
        void frameOut();
    };

    class QuitBtn {
    public:
        void calcAnm(); // 0x8018ba70

        // Inline/Unused
        void searchPane(J2DScreen *);
        void setBck(void *, J2DAnmTransform *);
        void setBtk(void *, J2DScreen *);
        void setBpk(void *, J2DScreen *);
        void setBrk(void *, J2DScreen *);
        void init();
        void frameIn();
        void frameOut();
        void unselect();
        void selected();

        static const u64 mscaPaneTag[5]; // 0x80375da8
    };

    SceneGhostLoadSave(JKRArchive *, JKRHeap *); // 0x8018e640
    virtual ~SceneGhostLoadSave(); // 0x8018e930
    virtual void init(); // 0x8018e7b0
    virtual void draw(); // 0x8018e990
    virtual void calc(); // 0x8018ea40

    void startFadeIn(); // 0x8018ec44
    void checkCard(); // 0x8018ecf4
    void fadeIn(); // 0x8018efec
    void frameInSlot(); // 0x8018f004
    void selectSlot(); // 0x8018f01c
    void confirm(); // 0x8018f26c
    void frameOutSlot(); // 0x8018f308
    void frameInData(); // 0x8018f374
    void selectData(); // 0x8018f38c
    void ghostSaveLoad(); // 0x8018f4b4
    void frameOutData(); // 0x8018f5e0
    void nextScene(); // 0x8018f648
    void prevScene(); // 0x8018f768
    
    static SceneGhostLoadSave *mspSceneGhostLoadSave; // 0x80416370
private:
    int _c; // 0x0c
    u8 _10[0x211c - 0x10];
    int _211c; // 0x211c
    u8 _2120[0x2514 - 0x2120];
    int _2514; // 0x2514
}; // class SceneGhostLoadSave

#endif // SCENEGHOSTLOADSAVE_H
