#ifndef SCENEOPTION_H
#define SCENEOPTION_H

#include "Kameda/Scene.h"

class SceneOption : public Scene { // Autogenerated
public:
    SceneOption(JKRArchive *, JKRHeap *); // 0x8013d964
    void SceneOption_ConstructerOption(JKRHeap *); // 0x8013da78
    void SceneOption_ConstructerBack(JKRHeap *); // 0x8013e30c
    void init(); // 0x8013e39c
    void init_option(); // 0x8013e46c
    void init_back(); // 0x8013e674
    ~SceneOption(); // 0x8013e680
    void draw(); // 0x8013e728
    void calcAnmCursor(); // 0x8013e798
    void calcAnm(); // 0x8013eaf4
    void calcMatAnmCursor(); // 0x8013f058
    void calc(); // 0x8013f1b8
    void fadeIn(); // 0x8013f3f0
    void option(); // 0x8013f41c
    void soundplayer(); // 0x8013fa18
    void nextScene(); // 0x8013fd90
    void getJASoundMode(int); // 0x8013fe94
    void SceneChange_ExitOption(int); // 0x8013fed4
    void rumble(int); // 0x80140000
    void rumbleOff(int); // 0x80140058
    void save(); // 0x80140090
    void nosave(); // 0x80140254
    void osSetSound(int); // 0x801402d4
    
    static const u64 mTag_menu[7];           // 0x8036dbb8
    static const u64 mTag_secret[3];         // 0x8036dbf0
    static const u64 mTag_cursor[7];         // 0x8036dc08
    static const u64 mTag_submenu[6];        // 0x8036dc40
    static const u64 mTag_submenu_bgms[3];   // 0x8036dc70
    static const u64 mTag_cursorl1[6];       // 0x8036dc88
    static const u64 mTag_cursorr1[6];       // 0x8036dcb8
    static const u64 mTag_cursorl2[6];       // 0x8036dce8
    static const u64 mTag_cursorr2[6];       // 0x8036dd18
    static const u64 mTag_cursorl3[6];       // 0x8036dd48
    static const u64 mTag_cursorr3[6];       // 0x8036dd78
    static const u64 mTag_cursorl4[6];       // 0x8036dda8
    static const u64 mTag_cursorr4[6];       // 0x8036ddd8
    static const u64 mTag_submenumoji[6];    // 0x8036de08
    static const u64 mTag_color[2];          // 0x8036de38
    static const u64 mTag_knob[2];           // 0x8036de48
    static const u64 mTag_volume[2];         // 0x8036de58
    static const u64 mTagSP_menu[4];         // 0x8036df50
    static const u64 mTagSP_submenu[3];      // 0x8036df70
    static const u64 mTagSP_cursor[4];       // 0x8036df88
    static const u64 mTagSP_cursorl1[3];     // 0x8036dfa8
    static const u64 mTagSP_cursorr1[3];     // 0x8036dfc0
    static const u64 mTagSP_cursorl2[3];     // 0x8036dfd8
    static const u64 mTagSP_cursorr2[3];     // 0x8036dff0
    static const u64 mTagSP_cursorl3[3];     // 0x8036e008
    static const u64 mTagSP_cursorr3[3];     // 0x8036e020
    static const u64 mTagSP_cursorl4[3];     // 0x8036e038
    static const u64 mTagSP_cursorr4[3];     // 0x8036e050
    static const u64 mTagSP_numeral1[3];     // 0x8036e068
    static const u64 mTagSP_numeral21[3];    // 0x8036e080
    static const u64 mTagSP_numeral22[3];    // 0x8036e098
    static const u64 mTagSP_numeral31[3];    // 0x8036e0b0
    static const u64 mTagSP_numeral32[3];    // 0x8036e0c8
    static const u64 mTagSP_numeral33[3];    // 0x8036e0e0
    static const u64 mTagSP_color[2];        // 0x8036e0f8
    static const char *mBtiName_sound[3];    // 0x80394bc8
    static const char *mBtiName_itemSlot[4]; // 0x80394bd4
    static const char *mBtiName_onOff[2];    // 0x804145b8
    static const char *mBtiName_bgmsign[2];  // 0x804145c0
    // Inline/Unused
    void SceneOption_ConstructerSoundPlayer(JKRHeap *);
    void init_blo();
    void init_soundplayer();
    void calcAnmAll();
    void calcAnmMenu();
    void calcAnmVolume();
    void calcTexChange();
    void calcAnmSPAll();
    void calcAnmSPMenu();
    void calcAnmSPCursor();
    void calcAnmSPNumeral();
    void calcMatAnmVolume();
    void calcMatAnmSPCursor();
    void calcMatAnmBack();
    void calcMatAnm();
    void isMenuExist(int);
    void IsChangeOptions();
    
    static const char *mBtiName_default;
    static const u64 mTag_all;
    static const u64 mTag_submenu_bgm;
    static const u64 mTag_osusume;
    static const u64 mTagSP_all;

private:
    u8 _c[0x58 - 0xc];
    int _58; // 0x58
    int _5c; // 0x5c
    u8 _60[0xa0 - 0x60];
    int _a0; // 0xa0
}; // class SceneOption
#endif // SCENEOPTION_H
