#ifndef SCENEMAP_H
#define SCENEMAP_H

#include "Kameda/Scene.h"

class SceneMap : public Scene { // Autogenerated
public:
    SceneMap(JKRArchive *, JKRHeap *); // 0x80145598
    virtual ~SceneMap(); // 0x801455f4
    virtual void init(); // 0x801455e8
    virtual void draw(); // 0x8014564c
    virtual void calc(); // 0x80145650

    void map(); // 0x8014570c
    void nextScene(); // 0x8014599c
    void nextRace(); // 0x80145a30
    void nextAward(); // 0x80145ca0
    void nextEnding(); // 0x80146148
    void nextTrueEnding(); // 0x801461c4

private:
    u32 _c; // 0x0c
}; // class SceneMap
#endif // SCENEMAP_H
