#ifndef SCENERECORD_H
#define SCENERECORD_H

#include "kartEnums.h"
#include "Kameda/Scene.h"

class SceneRecord : public Scene { // Autogenerated
public:
    SceneRecord(JKRArchive *, JKRHeap *); // 0x8014041c
    void SceneRecord_ConstructerMenu(JKRHeap *); // 0x801405f0
    void SceneRecord_ConstructerGP(JKRHeap *); // 0x80140b00
    void SceneRecord_ConstructerGPLine(JKRHeap *); // 0x80140e74
    void SceneRecord_ConstructerTA(JKRHeap *); // 0x80141214
    void SceneRecord_ConstructerTALine(JKRHeap *); // 0x80141758
    void SceneRecord_ConstructerBack(JKRHeap *); // 0x80141aa0
    void init(); // 0x80141b30
    void init_mode(); // 0x80141c68
    void init_gp(); // 0x80141d08
    void init_gpline(); // 0x80141d50
    void init_ta(); // 0x80141ec0
    void init_taline(); // 0x80141fb4
    void init_back(); // 0x801420e0
    ~SceneRecord(); // 0x801420ec
    void draw(); // 0x8014224c
    void calcAnmRecordCursor(); // 0x80142458
    void calcAnmRecordGPCursor(); // 0x80142738
    void calcAnmRecordGPLineAll(); // 0x80142904
    void calcTexChangeRecordGPLine(ERaceLevel); // 0x80142b38
    void calcAnmRecordTACursor(); // 0x801433c8
    void calcAnmRecordTALineAll(); // 0x80143594
    void calcTexChangeRecordTA(); // 0x801437c8
    void calcTexChangeRecordTALine(int); // 0x80143dd8
    void calcAnm(); // 0x80144420
    void calcMatAnmRecordCursor(); // 0x80144830
    void calcMatAnm(); // 0x801449c4
    void calc(); // 0x80144c54
    void fadeIn(); // 0x80144d20
    void mode(); // 0x80144d4c
    void gp(); // 0x801450dc
    void ta(); // 0x801451e8
    void record(); // 0x801452f4
    void piece(); // 0x801452f8
    void nextScene(); // 0x801452fc
    void ConvNum2ERace(int); // 0x801453e8
    
    static const u64 mTagRecord_cursor[3]; // 0x8036e1e8
    static const u64 mTagRecord_menu[3]; // 0x8036e200
    static const u64 mTagRecord_menubar[3]; // 0x8036e218
    static const u64 mTagRecord_submenu[2]; // 0x8036e230
    static const u64 mTagRecord_submenu2[6]; // 0x8036e240
    static const u64 mTagRecord_submenucursor[4]; // 0x8036e270
    static const u64 mTagRecord_submenucursor2[4]; // 0x8036e290
    static const u64 mTagRecord_submenucursor3[4]; // 0x8036e2b0
    static const u64 mTagRecordGP_all[3]; // 0x8036e2d0
    static const u64 mTagRecordGP_cursor[2]; // 0x8036e2e8
    static const u64 mTagRecordGP_cursor2[2]; // 0x8036e2f8
    static const u64 mTagRecordGP_cursor3[2]; // 0x8036e308
    static const u64 mTagRecordGP_cursorbtk[2]; // 0x8036e318
    static const u64 mTagRecordGP_linepostag[4]; // 0x8036e328
    static const u64 mTagRecordGP_linepostag2[4]; // 0x8036e348
    static const u64 mTagRecordGPLine_time[7]; // 0x8036e368
    static const u64 mTagRecordGPLine_quotation[2]; // 0x8036e3a0
    static const u64 mTagRecordGPLine_point[3]; // 0x8036e3b0
    static const u64 mTagRecordGPLine_charawindow[3]; // 0x8036e3c8
    static const u64 mTagRecordGPLine_name[3]; // 0x8036e3e0
    static const u64 mTagRecordTA_all[3]; // 0x8036e3f8
    static const u64 mTagRecordTA_cursor[2]; // 0x8036e410
    static const u64 mTagRecordTA_cursor2[2]; // 0x8036e420
    static const u64 mTagRecordTA_cursor3[2]; // 0x8036e430
    static const u64 mTagRecordTA_cursorbtk[2]; // 0x8036e440
    static const u64 mTagRecordTA_character[3]; // 0x8036e450
    static const u64 mTagRecordTA_characterwindow[3]; // 0x8036e468
    static const u64 mTagRecordTA_bestlap[7]; // 0x8036e480
    static const u64 mTagRecordTA_name[3]; // 0x8036e4b8
    static const u64 mTagRecordTA_quotation[2]; // 0x8036e4d0
    static const u64 mTagRecordTA_linepostag[5]; // 0x8036e4e0
    static const u64 mTagRecordTA_linecolor[5]; // 0x8036e508
    static const u64 mTagRecordTALine_time[7]; // 0x8036e530
    static const u64 mTagRecordTALine_quotation[2]; // 0x8036e568
    static const u64 mTagRecordTALine_character[3]; // 0x8036e578
    static const u64 mTagRecordTALine_characterwindow[3]; // 0x8036e590
    static const u64 mTagRecordTALine_name[3]; // 0x8036e5a8
    static const u64 mModeTag[6]; // 0x8036e788
    static const char *mBtiName_Cup[5]; // 0x80394c38
    static const char *mBtiName_Level[4]; // 0x80394c4c
    static const char *mBtiName_Rank[5]; // 0x80394c5c
    static const char *mBtiName_characterwindow; // 0x804145c8
    static const char *mBtiName_colon1; // 0x804145cc
    static const char *mBtiName_colon2; // 0x804145d0

    // Inline/Unused
    void calcAnmRecordAll();
    void calcTexChangeRecord();
    void calcAnmRecordGPAll();
    void calcAnmRecordGPLineEtc();
    void calcTexChangeRecordGP();
    void calcAnmRecordTAAll();
    void calcMatAnmRecordMenu();
    void calcMatAnmRecordGPCursor();
    void calcMatAnmRecordTACursor();
    void calcMatAnmRecordBack();
    void getKartID(EKartID);

    static const char *mBtiName_Trophy[3];
    static const char *mBtiName_quotation;
    static const char *mBtiName_minus;
    //static const u64 mTagRecord_all;
    //static const u64 mTagRecordGP_cup;
    //static const u64 mTagRecordGPLine_all;
    //static const u64 mTagRecordGPLine_level;
    //static const u64 mTagRecordGPLine_trophy;
    //static const u64 mTagRecordGPLine_pts;
    //static const u64 mTagRecordGPLine_chara1;
    //static const u64 mTagRecordGPLine_chara2;
    //static const u64 mTagRecordGPLine_kart;
    //static const u64 mTagRecordGPLine_tag;
    //static const u64 mTagRecordTA_course;
    //static const u64 mTagRecordTALine_all;
private:
    u8 _c[0x84 - 0xc];
    int _84; // 0x84
    int _88; // 0x88
    u8 _8c[0xa0 - 0x8c];
    int _a0; // 0xa0
}; // class SceneRecord
#endif // SCENERECORD_H
